feat: retry button; reduce loading time; path alias
baptistecdr/aria2-integration-safari pull request #17
Opened 2024-01-28 05:16 UTC by 838239178

### Add a retry button

Allowing the user to retry the download in error status

<img width="541" alt="截屏2024-01-28 13 06 59" src="https://github.com/baptistecdr/aria2-integration-safari/assets/55338151/2c4760bc-f73c-4172-b9b5-7384800d322a">

### Reduce loading time

Executing function before setting an interval

### Path alias

Add a vite plugin to support tsconfig option: path

2024-01-28 08:26 UTC, baptistecdr requested changes
Nice work, thank you !

2024-01-28 08:26 UTC, baptistecdr commented on package.json
> +    "build:watch": "nodemon --watch . --exec yarn run build"
Keep using npm. The project is small enough to be handle by npm.

2024-01-28 08:26 UTC, baptistecdr commented on src/popup/models/task.ts
> +  cachedFileName?: string;
`cachedFileName` -> `cachedFilename`

2024-01-28 08:26 UTC, baptistecdr commented on src/popup/components/server-tab.tsx
> +  let updateTasks = async () => {
Use function declaration instead of function expression

2024-01-28 08:26 UTC, baptistecdr commented on src/popup/components/server-task.tsx
> +  let fname = "";
`fname` -> `filename`

2024-01-28 08:26 UTC, baptistecdr commented on package.json
> +    "vite-tsconfig-paths": "^4.3.1",
You should move the dependency at the end to keep the alphabetical order.

2024-01-28 10:54 UTC, baptistecdr commented
I created a different pipeline for pull request. Could you rebase on that and fix the linter issues:

> 
> /Users/baptistecdr/Downloads/aria2-integration-safari/src/popup/components/server-tab.tsx
>   72:6  warning  React Hook useEffect has a missing dependency: 'updateTasks'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
> 
> /Users/baptistecdr/Downloads/aria2-integration-safari/src/popup/components/server-task-management.tsx
>    2:22  error  Missing file extension for "@/popup/models/task"       import/extensions
>    3:28  error  Missing file extension for "@/models/aria2-extension"  import/extensions
>    4:20  error  Missing file extension for "@/models/server"           import/extensions
>   19:99  error  Insert `;`                                             prettier/prettier
> 
> /Users/baptistecdr/Downloads/aria2-integration-safari/src/popup/components/server-task.tsx
>    6:22  error  Missing file extension for "@/popup/models/task"     import/extensions
>    7:26  error  Missing file extension for "@/stdlib"                import/extensions
>    9:18  error  Missing file extension for "@/i18n"                  import/extensions
>   10:20  error  Missing file extension for "@/models/server"         import/extensions
>   27:3   error  Assignment to property of function parameter 'task'  no-param-reassign
>   27:33  error  Insert `;`                                           prettier/prettier
>   28:18  error  Insert `;`                                           prettier/prettier

`Missing file extension for` > https://stackoverflow.com/a/72643821 should do the trick :)

2024-01-29 11:11 UTC, 838239178 commented
@baptistecdr Done it.

2024-01-29 11:33 UTC, merged

2024-01-29 12:53 UTC, baptistecdr commented
@838239178 , do you need a redeem code for the app? :)

2024-01-29 13:04 UTC, 838239178 commented
@baptistecdr Thanks but I have bought it.